name: Run Selenium Tests

on:
  workflow_dispatch:   # 👈 allows manual trigger from GitHub Actions tab

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up Java (adjust version to your project, e.g. 11, 17, 21)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Install Chrome browser
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # 4. Install ChromeDriver
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+' | head -1)
          sudo apt-get install -y chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

      # 5. Build project with Maven
      - name: Build with Maven
        run: mvn clean install -B

      # 6. Run TestNG Selenium tests
      - name: Run tests
        run: mvn test
